
# build: docker build -t <name> .
# run: docker run -it -p 1883:1883 -p 9001:9001 -v <path to>/mosquitto.conf:/mosquitto/config/mosquitto.conf <container name>

FROM eclipse-mosquitto

RUN apk add openvpn


